### ISSUE TITLE
Apache Tomcat mirror not found

### ISSUE THREAD

**Issue by ronna** [jefferyb/Kuali-Coeus-Install-Script#1]
Hi Jeffery,

The apache tomcat mirror can not be found:

--2015-10-07 15:11:40--  http://apache.mirrors.lucidnetworks.net/tomcat/tomcat-8/v8.0.21/bin/apache-tomcat-8.0.21.tar.gz
Resolving apache.mirrors.lucidnetworks.net (apache.mirrors.lucidnetworks.net)... 108.166.161.136
Connecting to apache.mirrors.lucidnetworks.net (apache.mirrors.lucidnetworks.net)|108.166.161.136|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-10-07 15:11:41 ERROR 404: Not Found.

tar (child): apache-tomcat-8.0.21.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

**Comment by jefferyb** [comment]
Hi Ronald,
Thanks for letting me know... I just fixed it, if you want to give it a try,  so that it will get whatever the latest version is currently available on the tomcat website...
Thanks again,
Jeffery
